; Configuration PHP personnalisée

; Activer les logs d'erreur
error_log = "logs/php_error.log"

; Niveau de rapport des erreurs
error_reporting = E_ALL
display_errors = Off

; Log des erreurs
log_errors = On

; Autres configurations
memory_limit = 256M
max_execution_time = 300
upload_max_filesize = 128M
post_max_size = 128M

; Configuration de la session
session.save_path = "/home/tdlafpa21/tmp"
session.gc_maxlifetime = 1440

; Configuration de l'upload de fichiers
file_uploads = On

; Configuration de la sécurité
allow_url_fopen = On

; Configuration de l'extension PDO
pdo_mysql.cache_size = 2000
pdo_mysql.default_socket = "/var/run/mysqld/mysqld.sock"