; Activer l'affichage des erreurs (pour le débogage)
display_errors = On
display_startup_errors = On

; Activer la journalisation des erreurs
log_errors = On

; Spécifier le chemin du fichier de log d'erreurs
; Le chemin doit être absolu pour assurer l'écriture des logs.
; Assurez-vous que le dossier C:\Temp existe et que le serveur web a les permissions d'écriture.
error_log = ./php_error.log

; Rapporter toutes les erreurs PHP
error_reporting = E_ALL